import '../styles/globals.css'
import SideBar from '@/components/SideBar'

export const metadata = {
  title: 'Simple ChatGPT',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <div className='flex'>
          <div className='bg-slate-900 max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'>
            {/* Sidebar */}
            <SideBar/>

          </div>


          {/* Client Provider - Notification */}

          <div className='bg-slate-800 flex-1'>{children}</div>
        </div> 
      </body>
    </html>
  )
}
